const USE_AUTH_QUERY_KEY = "AUTH_QUERY";
const USE_NEW_MOVIES_AND_SERIES_QUERY_KEY = "NEW_MOVIES_AND_SERIES_QUERY";
const USE_UPCOMING_MOVIES_QUERY_KEY = "UPCOMING_MOVIES_QUERY";
const USE_TRENDING_SERIES_QUERY_KEY = "TRENDING_SERIES_QUERY";
const USE_NOW_PLAYING_MOVIES_QUERY_KEY = "NOW_PLAYING_MOVIES_QUERY";
const USE_MOVIE_QUERY_KEY = "MOVIE_QUERY";
const USE_MOVIE_VIDEOS_QUERY_KEY = "MOVIE_VIDEOS_QUERY";

export {
  USE_AUTH_QUERY_KEY,
  USE_NEW_MOVIES_AND_SERIES_QUERY_KEY,
  USE_UPCOMING_MOVIES_QUERY_KEY,
  USE_TRENDING_SERIES_QUERY_KEY,
  USE_NOW_PLAYING_MOVIES_QUERY_KEY,
  USE_MOVIE_QUERY_KEY,
  USE_MOVIE_VIDEOS_QUERY_KEY,
};
